# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: my hobby
email: blastingzone@naver.com
description: 게임, 취미
baseurl: "/gameBlog" # the subpath of your site, e.g. /blog
url: "http://blastingzone.github.io" # the base hostname & protocol for your site
github_username:  blastingzone

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Tag Page
collections:
  tags:
    output: true
    permalink: /tags/:path/
defaults:
  - scope:
      path: ''
      type: tags
    values:
      layout: tag
